### ISSUE TITLE
Both missing and cutoff mode

### ISSUE THREAD

**Issue by theg00s3** [Migz93/lidarr-smloadr-script#31]
Is it possible for the script to run in both missing and cutoff mode?

**Comment by RandomNinjaAtk** [comment]
Not currently. I may try to update it for that, you could set it to use artist mode to pull everything. But this may update or replace existing files you have already matched with lidarr with new versions

**Comment by RandomNinjaAtk** [comment]
A new version of this is built and supports this request, located here: https://github.com/RandomNinjaAtk/lidarr-automated-downloader
