### ISSUE TITLE
SMLoadr 1.10.0 removes -p flag

### ISSUE THREAD

**Issue by verbxd** [Migz93/lidarr-smloadr-script#32]
See SMLoadr issue [#72](https://git.fuwafuwa.moe/SMLoadrDev/SMLoadr/issues/72)

Probably best to recommend compiling SMLoadr 1.9.5 until then. It seems the dev has removed the release for it.

**Comment by Migz93** [comment]
Thanks for highlighting this, we're moving away from SMLoadr and things like this solidifies our choice to look at alternatives.

Using either Master or Develop branch, rename/remove the SMLoadr executable and the script will take care of downloading an alternative called d-fi which works almost exactly the same.

Will see what @RandomNinjaAtk think's as he's really the brains behind the script now, unsure if we'll push some temp fix to remove SMLoadr support and only use d-fi in master/develop or if maybe the Deezloader Remix branch is ready for prime time.

**Comment by RandomNinjaAtk** [comment]
Use the remix Branch with deezloader or the Dev branch with d-fi. There is no plan to fix it and remix is the path forward

**Comment by staticn0de** [comment]
Is the remix branch ready for general use? I'm on the develop branch now  have it working in docker with lidarr but may as well move over the remix if its ready to go. 

Thanks for the work you have done on this script, its completely changed the way I use lidarr.

**Comment by RandomNinjaAtk** [comment]
Yes, the remix Branch is fully functional. Just no documentation for the client change.

**Comment by RandomNinjaAtk** [comment]
They resolved this in an app update
