### ISSUE TITLE
(%artist_id%) - not valid for the Album template type

### ISSUE THREAD

**Issue by staticn0de** [Migz93/lidarr-smloadr-script#34]
Hi there,

I've setup the dremix branch so that its mostly working with deezloader 4.3.0.

One thing I noticed is that the recommended naming from the config.sample file has the (%artist_id%) variable for the album template. 

(%artist_id%) is not a valid variable for album template so it does not populate.

**Comment by Migz93** [comment]
Please check out https://github.com/RandomNinjaAtk/lidarr-automated-downloader as a replacement for this script. This script is now deprecated and the above script replaces/improves upon it.
